Bump crypto to 0.4.0
machikado-network/tubuyaita pull request #27
Opened 2022-08-22 14:06 UTC by sizumita

close #21

2022-08-22 14:25 UTC, tignear requested changes

2022-08-22 14:25 UTC, tignear commented on tubuyaita/lib/tubuyaita_web/cursor.ex
> +         {:ok, contents_hash} when is_binary(contents_hash) <- Crypto.from_hex(contents_hash) do
is_binaryいらない気がする

2022-08-22 14:25 UTC, tignear requested changes

2022-08-22 14:25 UTC, tignear commented on tubuyaita/lib/tubuyaita/crypto.ex
> +  @spec hash(String.t()) :: binary()
入力がbinaryで出力がStringであるべき

2022-08-22 14:27 UTC, tignear commented on tubuyaita/lib/tubuyaita/crypto.ex
> +  @spec hash(String.t()) :: binary()
ちゃうわ。両方binaryであるべきだわ

2022-08-22 14:27 UTC, sizumita commented on tubuyaita/lib/tubuyaita/crypto.ex
> +  @spec hash(String.t()) :: binary()
草

2022-08-24 01:31 UTC, tignear approved these changes

2022-08-24 01:31 UTC, tignear commented on tubuyaita/test/tubuyaita/users/put_test.exs
> +    IO.inspect public
これは残す方針?

2022-08-24 01:47 UTC, merged