list messages
machikado-network/tubuyaita pull request #6
Opened 2022-08-12 13:12 UTC by tignear

2022-08-18 15:01 UTC, tignear commented
link header吐いてないや

2022-08-19 13:06 UTC, sizumita requested changes

2022-08-19 13:06 UTC, sizumita commented on tubuyaita/lib/tubuyaita/message/service.ex
> +    with {:ok, %{"timestamp" => timestamp}} <- Jason.decode(contents),
ここ500でちゃうなって昨日気がついた

2022-08-19 13:06 UTC, sizumita commented on tubuyaita/lib/tubuyaita_web/views/api/v1/messages_view.ex
> +        contents_hash: Base.url_encode64(e.contents_hash),
これhexじゃなくね？
ソケットの方ではCrypto.to_hexをつかってる

2022-08-19 13:06 UTC, sizumita commented on tubuyaita/lib/tubuyaita_web/views/api/v1/messages_view.ex
> +        public_key: Base.url_encode64(e.public_key),
ここも

2022-08-19 13:08 UTC, sizumita commented on tubuyaita/lib/tubuyaita_web/views/api/v1/messages_view.ex
> +        contents_hash: Base.url_encode64(e.contents_hash),
テストのほうもこれassert equalsした方がいいかも？

2022-08-19 13:54 UTC, tignear commented on tubuyaita/lib/tubuyaita_web/views/api/v1/messages_view.ex
> +        contents_hash: Base.url_encode64(e.contents_hash),
hexだって全く承知してなかった。ok

2022-08-20 05:42 UTC, sizumita requested changes

2022-08-20 05:42 UTC, sizumita commented on tubuyaita/lib/tubuyaita/crypto.ex
> +  @spec from_hex(String.t()) :: binary() | {:error, :invalid_hex_string}
これ`{:ok, binary()} || {:error, :invalid_hex_string}`だったかも

2022-08-20 08:56 UTC, sizumita commented on tubuyaita/lib/tubuyaita/crypto.ex
> +  @spec from_hex(String.t()) :: binary() | {:error, :invalid_hex_string}
他のPRで直す！

2022-08-20 08:56 UTC, sizumita approved these changes

2022-08-20 12:38 UTC, tignear commented
なんか錯乱して変なことした気がする

2022-08-20 12:38 UTC, sizumita commented
草

2022-08-20 12:40 UTC, tignear commented
ok

2022-08-20 12:40 UTC, sizumita commented
CI終わったらマージします

2022-08-20 13:44 UTC, merged